# core config placeholder
MIN_RR_RATIO = 2.0
MAX_SPREAD = 15.0
MIN_CONFLUENCE_SCORE = 70.0
MAX_CRISIS_SCORE = 30.0
MAX_MC_DISPERSION = 5.0
MAX_DAILY_DRAWDOWN = 1000.0
MAX_TRADES_PER_DAY = 5
COOLDOWN_BARS = 3
